name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: bison flex libbison-dev libfl-dev
          version: 1.0
      - name: Build cmm
        run: make
        working-directory: ./cmm
      - name: Build pl0i
        run: make
        working-directory: ./pl0i_src
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            ./cmm/cmm
            ./pl0i_src/pl0i

  test-01:
    name: Test Factorial
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: chmod
        run: |
          chmod +x ./cmm/cmm
          chmod +x ./pl0i_src/pl0i
      - name: Create source file
        run: |
          cat << EOF > code.cmm
          fact(n) {
            if n < 1 then return 1;
            else return n * fact(n - 1);
            endif;
          }

          main {
            var n;
            read n;
            write fact(n);
            writeln;
          }
          EOF
        working-directory: ./cmm
      - name: Generate code.output
        run: |
          ./cmm < code.cmm 2> err.txt
          if [ -s err.txt ]; then
            cat err.txt
            exit 1
          fi
        working-directory: ./cmm
      - name: Move code.output
        run: mv code.output ../pl0i_src
        working-directory: ./cmm
      - name: Create sample input
        run: |
          cat << EOF > input.txt
          5
          EOF
        working-directory: ./pl0i_src
      - name: Run code.pl0i
        run: ./pl0i < input.txt > output.txt
        working-directory: ./pl0i_src
      - name: Create expected output
        run: |
          cat << EOF > expected.txt
          120
          EOF
        working-directory: ./pl0i_src
      - name: Compare output
        run: |
          echo ::group::output.txt
          cat -n output.txt
          echo ::endgroup::
          echo ::group::expected.txt
          cat -n expected.txt
          echo ::endgroup::
          echo ::group::diff
          diff output.txt expected.txt || true
          echo ::endgroup::
        working-directory: ./pl0i_src

  test-02:
    name: Test Modulo
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: chmod
        run: |
          chmod +x ./cmm/cmm
          chmod +x ./pl0i_src/pl0i
      - name: Create source file
        run: |
          cat << EOF > code.cmm
          main {
            var a, b;
            read a;
            read b;
            write a % b;
            writeln;
            read a;
            read b;
            write a % b;
            writeln;
            read a;
            read b;
            write a % b;
            writeln;
            read a;
            read b;
            write a % b;
            writeln;
            read a;
            read b;
            write a % b;
            writeln;
            read a;
            read b;
            write a % b;
            writeln;
            read a;
            read b;
            write a % b;
            writeln;
            read a;
            read b;
            write a % b;
            writeln;
          }
          EOF
        working-directory: ./cmm
      - name: Generate code.output
        run: |
          ./cmm < code.cmm 2> err.txt
          if [ -s err.txt ]; then
            cat err.txt
            exit 1
          fi
        working-directory: ./cmm
      - name: Move code.output
        run: mv code.output ../pl0i_src
        working-directory: ./cmm
      - name: Create sample input
        run: |
          cat << EOF > input.txt
          5
          3
          5
          -3
          5
          10
          5
          -10
          -5
          3
          -5
          -3
          -5
          10
          -5
          -10
          EOF
        working-directory: ./pl0i_src
      - name: Run code.pl0i
        run: ./pl0i < input.txt > output.txt
        working-directory: ./pl0i_src
      - name: Create expected output
        run: |
          cat << EOF > expected.txt
          2
          2
          5
          5
          -2
          -2
          -5
          -5
          EOF
        working-directory: ./pl0i_src
      - name: Compare output
        run: |
          echo ::group::output.txt
          cat -n output.txt
          echo ::endgroup::
          echo ::group::expected.txt
          cat -n expected.txt
          echo ::endgroup::
          echo ::group::diff
          diff output.txt expected.txt || true
          echo ::endgroup::
        working-directory: ./pl0i_src

  test-03:
    name: Test Modulo (Floating Point Exception)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: chmod
        run: |
          chmod +x ./cmm/cmm
          chmod +x ./pl0i_src/pl0i
      - name: Create source file
        run: |
          cat << EOF > code.cmm
          main {
            var a, b;
            read a;
            read b;
            write a % b;
            writeln;
          }
          EOF
        working-directory: ./cmm
      - name: Generate code.output
        run: |
          ./cmm < code.cmm 2> err.txt
          if [ -s err.txt ]; then
            cat err.txt
            exit 1
          fi
        working-directory: ./cmm
      - name: Move code.output
        run: mv code.output ../pl0i_src
        working-directory: ./cmm
      - name: Create sample input
        run: |
          cat << EOF > input.txt
          5
          0
          EOF
        working-directory: ./pl0i_src
      - name: Run code.pl0i
        run: ./pl0i < input.txt > output.txt || true
        working-directory: ./pl0i_src
      - name: Create expected output
        run: |
          cat << EOF > expected.txt
          Floating Point Exception
          EOF
        working-directory: ./pl0i_src
      - name: Compare output
        run: |
          echo ::group::output.txt
          cat -n output.txt
          echo ::endgroup::
          echo ::group::expected.txt
          cat -n expected.txt
          echo ::endgroup::
          echo ::group::diff
          diff output.txt expected.txt || true
          echo ::endgroup::
        working-directory: ./pl0i_src

  test-04:
    name: Test Power
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: chmod
        run: |
          chmod +x ./cmm/cmm
          chmod +x ./pl0i_src/pl0i
      - name: Create source file
        run: |
          cat << EOF > code.cmm
          main {
            var a, b;
            read a;
            read b;
            write a ^ b;
            writeln;
            read a;
            read b;
            write a ^ b;
            writeln;
            read a;
            read b;
            write a ^ b;
            writeln;
            read a;
            read b;
            write a ^ b;
            writeln;
            read a;
            read b;
            write a ^ b;
            writeln;
            read a;
            read b;
            write a ^ b;
            writeln;
            read a;
            read b;
            write a ^ b;
            writeln;
            read a;
            read b;
            write a ^ b;
            writeln;
            read a;
            read b;
            write a ^ b;
            writeln;
            read a;
            read b;
            write a ^ b;
            writeln;
            write 2 * 3 ^ 3;
            write 2 ^ 2 ^ 2;
            writeln;
          }
          EOF
        working-directory: ./cmm
      - name: Generate code.output
        run: |
          ./cmm < code.cmm 2> err.txt
          if [ -s err.txt ]; then
            cat err.txt
            exit 1
          fi
        working-directory: ./cmm
      - name: Move code.output
        run: mv code.output ../pl0i_src
        working-directory: ./cmm
      - name: Create sample input
        run: |
          cat << EOF > input.txt
          5
          0
          5
          1
          5
          2
          5
          3
          5
          -1
          -5
          0
          -5
          1
          -5
          2
          -5
          3
          -5
          -1
          EOF
        working-directory: ./pl0i_src
      - name: Run code.pl0i
        run: ./pl0i < input.txt > output.txt || true
        working-directory: ./pl0i_src
      - name: Create expected output
        run: |
          cat << EOF > expected.txt
          1
          5
          25
          125
          1
          1
          -5
          25
          -125
          1
          54 16
          EOF
        working-directory: ./pl0i_src
      - name: Compare output
        run: |
          echo ::group::output.txt
          cat -n output.txt
          echo ::endgroup::
          echo ::group::expected.txt
          cat -n expected.txt
          echo ::endgroup::
          echo ::group::diff
          diff output.txt expected.txt || true
          echo ::endgroup::
        working-directory: ./pl0i_src

  test-05:
    name: Test Goto
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: chmod
        run: |
          chmod +x ./cmm/cmm
          chmod +x ./pl0i_src/pl0i
      - name: Create source file
        run: |
          cat << EOF > code.cmm
          main {
            var a, b;
            read a;
            read b;
            if a < b then goto c;
            else goto d;
            endif;
            c:
            write a;
            goto e;
            d:
            write b;
            goto f;
            e:
            writeln;
            goto d;
            f:
            writeln;
          }
          EOF
        working-directory: ./cmm
      - name: Generate code.output
        run: |
          ./cmm < code.cmm 2> err.txt
          if [ -s err.txt ]; then
            cat err.txt
            exit 1
          fi
        working-directory: ./cmm
      - name: Move code.output
        run: mv code.output ../pl0i_src
        working-directory: ./cmm
      - name: Create sample input 1
        run: |
          cat << EOF > input.txt
          1
          2
          EOF
        working-directory: ./pl0i_src
      - name: Run code.pl0i 1
        run: ./pl0i < input.txt > output.txt || true
        working-directory: ./pl0i_src
      - name: Create expected output 1
        run: |
          cat << EOF > expected.txt
          1
          2
          EOF
        working-directory: ./pl0i_src
      - name: Compare output 1
        run: |
          echo ::group::output.txt
          cat -n output.txt
          echo ::endgroup::
          echo ::group::expected.txt
          cat -n expected.txt
          echo ::endgroup::
          echo ::group::diff
          diff output.txt expected.txt || true
          echo ::endgroup::
        working-directory: ./pl0i_src
      - name: Create sample input 2
        run: |
          cat << EOF > input.txt
          2
          1
          EOF
        working-directory: ./pl0i_src
      - name: Run code.pl0i 2
        run: ./pl0i < input.txt > output.txt || true
        working-directory: ./pl0i_src
      - name: Create expected output 2
        run: |
          cat << EOF > expected.txt
          1
          EOF
        working-directory: ./pl0i_src
      - name: Compare output 2
        run: |
          echo ::group::output.txt
          cat -n output.txt
          echo ::endgroup::
          echo ::group::expected.txt
          cat -n expected.txt
          echo ::endgroup::
          echo ::group::diff
          diff output.txt expected.txt || true
          echo ::endgroup::
        working-directory: ./pl0i_src

  test-06:
    name: Test Func Each Other
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: chmod
        run: |
          chmod +x ./cmm/cmm
          chmod +x ./pl0i_src/pl0i
      - name: Create source file
        run: |
          cat << EOF > code.cmm
          func1(n) {
            if n < 1 then return 0;
            else return n + func2(n - 1);
            endif;
          }
          func2(n) {
            if n < 1 then return 1;
            else return n * func1(n - 1);
            endif;
          }
          main {
            var n;
            read n;
            write func1(n);
            writeln;
            read n;
            write func1(n);
            writeln;
            read n;
            write func1(n);
            writeln;
            read n;
            write func1(n);
            writeln;
            read n;
            write func1(n);
            writeln;
            read n;
            write func1(n);
            writeln;
            read n;
            write func1(n);
            writeln;
            read n;
            write func1(n);
            writeln;
            read n;
            write func1(n);
            writeln;
            read n;
            write func1(n);
            writeln;
          }
          EOF
        working-directory: ./cmm
      - name: Generate code.output
        run: |
          ./cmm < code.cmm 2> err.txt
          if [ -s err.txt ]; then
            cat err.txt
            exit 1
          fi
        working-directory: ./cmm
      - name: Move code.output
        run: mv code.output ../pl0i_src
        working-directory: ./cmm
      - name: Create sample input
        run: |
          cat << EOF > input.txt
          0
          1
          2
          3
          4
          5
          6
          7
          8
          9
          EOF
        working-directory: ./pl0i_src
      - name: Run code.pl0i
        run: ./pl0i < input.txt > output.txt || true
        working-directory: ./pl0i_src
      - name: Create expected output
        run: |
          cat << EOF > expected.txt
          0
          2
          2
          7
          10
          33
          56
          205
          400
          1649
          EOF
        working-directory: ./pl0i_src
      - name: Compare output
        run: |
          echo ::group::output.txt
          cat -n output.txt
          echo ::endgroup::
          echo ::group::expected.txt
          cat -n expected.txt
          echo ::endgroup::
          echo ::group::diff
          diff output.txt expected.txt || true
          echo ::endgroup::
        working-directory: ./pl0i_src

  test-07:
    name: Test plus plus and minus minus
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: chmod
        run: |
          chmod +x ./cmm/cmm
          chmod +x ./pl0i_src/pl0i
      - name: Create source file
        run: |
          cat << EOF > code.cmm
          main {
            var v;
            v := 0;
            write v;
            write v++;
            write v;
            writeln;
            v := 0;
            write v;
            write ++v;
            write v;
            writeln;
            v := 0;
            write v;
            write v--;
            write v;
            writeln;
            v := 0;
            write v;
            write --v;
            write v;
            writeln;
          }
          EOF
        working-directory: ./cmm
      - name: Generate code.output
        run: |
          ./cmm < code.cmm 2> err.txt
          if [ -s err.txt ]; then
            cat err.txt
            exit 1
          fi
        working-directory: ./cmm
      - name: Move code.output
        run: mv code.output ../pl0i_src
        working-directory: ./cmm
      - name: Run code.pl0i
        run: ./pl0i > output.txt || true
        working-directory: ./pl0i_src
      - name: Create expected output
        run: |
          cat << EOF > expected.txt
          0 0 1
          0 1 1
          0 0 -1
          0 -1 -1
          EOF
        working-directory: ./pl0i_src
      - name: Compare output
        run: |
          echo ::group::output.txt
          cat -n output.txt
          echo ::endgroup::
          echo ::group::expected.txt
          cat -n expected.txt
          echo ::endgroup::
          echo ::group::diff
          diff output.txt expected.txt || true
          echo ::endgroup::
        working-directory: ./pl0i_src

  test-08:
    name: Test For
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: chmod
        run: |
          chmod +x ./cmm/cmm
          chmod +x ./pl0i_src/pl0i
      - name: Create source file
        run: |
          cat << EOF > code.cmm
          main {
            var n, i, sum;
            read n;
            sum := 0;
            for i := 1; i <= n; i++; do {
              sum = sum + i;
            }
            write sum;
            writeln;
            read n;
            sum := 0;
            for i := 1; i <= n; i++; do {
              sum := sum + i;
            }
            write sum;
            writeln;
            read n;
            sum := 0;
            for i := 1; i <= n; i++; do {
              sum := sum + i;
            }
            write sum;
            writeln;
            read n;
            sum := 0;
            for i := 1; i <= n; i++; do {
              sum := sum + i;
            }
            write sum;
            writeln;
            read n;
            sum := 0;
            for i := 1; i <= n; i++; do {
              sum := sum + i;
            }
            write sum;
            writeln;
          }
          EOF
        working-directory: ./cmm
      - name: Generate code.output
        run: |
          ./cmm < code.cmm 2> err.txt
          if [ -s err.txt ]; then
            cat err.txt
            exit 1
          fi
        working-directory: ./cmm
      - name: Move code.output
        run: mv code.output ../pl0i_src
        working-directory: ./cmm
      - name: Create sample input
        run: |
          cat << EOF > input.txt
          0
          1
          2
          3
          4
          EOF
        working-directory: ./pl0i_src
      - name: Run code.pl0i
        run: ./pl0i < input.txt > output.txt || true
        working-directory: ./pl0i_src
      - name: Create expected output
        run: |
          cat << EOF > expected.txt
          0
          1
          3
          6
          10
          EOF
        working-directory: ./pl0i_src
      - name: Compare output
        run: |
          echo ::group::output.txt
          cat -n output.txt
          echo ::endgroup::
          echo ::group::expected.txt
          cat -n expected.txt
          echo ::endgroup::
          echo ::group::diff
          diff output.txt expected.txt || true
          echo ::endgroup::
        working-directory: ./pl0i_src
