name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bison flex libbison-dev libfl-dev
      - name: Build cmm
        run: make
        working-directory: ./cmm
      - name: Build pl0i
        run: make
        working-directory: ./pl0i_src
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            ./cmm/cmm
            ./pl0i_src/pl0i

  test-01:
    name: Test Factorial
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: chmod
        run: |
          chmod +x ./cmm/cmm
          chmod +x ./pl0i_src/pl0i
      - name: Create source file
        run: |
          cat << EOF > code.cmm
          fact(n) {
            if n < 1 then return 1;
            else return n * fact(n - 1);
            endif;
          }

          main {
            var n;
            read n;
            write fact(n);
            writeln;
          }
          EOF
        working-directory: ./cmm
      - name: Generate code.output
        run: |
          ./cmm < code.cmm 2> err.txt
          if [ -s err.txt ]; then
            cat err.txt
            exit 1
          fi
        working-directory: ./cmm
      - name: Move code.output
        run: mv code.output ../pl0i_src
        working-directory: ./cmm
      - name: Create sample input
        run: |
          cat << EOF > input.txt
          5
          EOF
        working-directory: ./pl0i_src
      - name: Run code.pl0i
        run: ./pl0i < input.txt > output.txt
        working-directory: ./pl0i_src
      - name: Create expected output
        run: |
          cat << EOF > expected.txt
          120
          EOF
        working-directory: ./pl0i_src
      - name: Compare output
        run: |
          echo ::group::output.txt
          cat -n output.txt
          echo ::endgroup::
          echo ::group::expected.txt
          cat -n expected.txt
          echo ::endgroup::
          echo ::group::diff
          diff output.txt expected.txt || true
          echo ::endgroup::
        working-directory: ./pl0i_src

  test-02:
    name: Test Modulo
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: chmod
        run: |
          chmod +x ./cmm/cmm
          chmod +x ./pl0i_src/pl0i
      - name: Create source file
        run: |
          cat << EOF > code.cmm
          main {
            var a, b;
            read a;
            read b;
            write a % b;
            writeln;
            read a;
            read b;
            write a % b;
            writeln;
            read a;
            read b;
            write a % b;
            writeln;
            read a;
            read b;
            write a % b;
            writeln;
            read a;
            read b;
            write a % b;
            writeln;
            read a;
            read b;
            write a % b;
            writeln;
            read a;
            read b;
            write a % b;
            writeln;
            read a;
            read b;
            write a % b;
            writeln;
            read a;
            read b;
            write a % b;
            writeln;
          }
          EOF
        working-directory: ./cmm
      - name: Generate code.output
        run: |
          ./cmm < code.cmm 2> err.txt
          if [ -s err.txt ]; then
            cat err.txt
            exit 1
          fi
        working-directory: ./cmm
      - name: Move code.output
        run: mv code.output ../pl0i_src
        working-directory: ./cmm
      - name: Create sample input
        run: |
          cat << EOF > input.txt
          5
          3
          5
          -3
          5
          10
          5
          -10
          -5
          3
          -5
          -3
          -5
          10
          -5
          -10
          5
          0
          EOF
        working-directory: ./pl0i_src
      - name: Run code.pl0i
        run: ./pl0i < input.txt > output.txt
        working-directory: ./pl0i_src
      - name: Create expected output
        run: |
          cat << EOF > expected.txt
          2
          2
          5
          5
          -2
          -2
          -5
          -5
          Floating point exception
          EOF
        working-directory: ./pl0i_src
      - name: Compare output
        run: |
          echo ::group::output.txt
          cat -n output.txt
          echo ::endgroup::
          echo ::group::expected.txt
          cat -n expected.txt
          echo ::endgroup::
          echo ::group::diff
          diff output.txt expected.txt || true
          echo ::endgroup::
        working-directory: ./pl0i_src
